name = "personal"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat_v2"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability.logs]
enabled = true

[[routes]]
pattern = "vishalk.com"
custom_domain = true

[[routes]]
pattern = "www.vishalk.com"
custom_domain = true
