name = "personal"
compatibility_date = "2025-09-11"
compatibility_flags = ["nodejs_compat_v2"]

[site]
bucket = "./build"

# Workers configuration for static site hosting
# This allows serving static assets through Cloudflare Workers
main = "./build/_worker.js"